import { AppModel } from '../types/App';

export const fetchApps = async (): Promise<AppModel[]> => {
  return new Promise((resolve) =>
    setTimeout(() => {
      resolve([
        {
          id: 1,
          applications: 'Revit',
          name: 'Place Wall Framing',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2024',
          category: 'Structure',
        },
        {
          id: 2,
          name: 'AutoCAD',
          applications: 'AutoCAD',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://play-lh.googleusercontent.com/y92LD5c5rdlNfquCy-YPNIvdnS4ISEL05wickp28OLya8WlmWQwXfAP0Yys9iTssny3K',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Architecture',
          version: '2023',
          category: 'Architecture',
        },
        {
          id: 3,
          name: 'Inventor',
          applications: 'Inventor',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://www.imaginit.com/Portals/4/ImageCache/ProductDetails/1_autodesk-inventor-professional-product-icon-128@2x.png',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2023',
          category: 'Structure',
        },
        {
          id: 4,
          name: 'Navisworks',
          applications: 'Navisworks',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://damassets.autodesk.net/content/dam/autodesk/www/product-imagery/svg/product-icon/full/navisworks-manage-full-product-icon.svg',
          type: 'Dynamo',
          vendor: 'Autodesk',
          discipline: 'MEP',
          version: '2023',
          category: 'Dynamo',
        },
        {
          id: 5,
          name: 'Tekla Structures',
          applications: 'Tekla Structures',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Trimble',
          type: 'Extensions',
          discipline: 'Structure',
          version: '2024',
          category: 'Creative',
          icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaqdiycjejPdZhrFq6APc_1s2lSyDmBW4kUA&s',
        },
        {
          id: 6,
          name: 'Tekla Structures Designer',
          applications: 'Tekla Structures Designer',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Trimble',
          type: 'Extensions',
          discipline: 'Structure',
          version: '2024',
          category: 'Development',
          icon: 'https://down-id.img.susercontent.com/file/a57e40169905a69329135442e053ec04_tn.webp',
        },
        {
          id: 7,
          name: 'SketchUp',
          applications: 'SketchUp',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Trimble',
          type: 'Addins',
          discipline: 'Architecture',
          version: '2023',
          category: 'Architecture',
          icon: 'https://axonware.com/catalog/images/sketchup-logo.png',
        },
        {
          id: 8,
          name: 'MicroStation',
          applications: 'MicroStation',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Bentley Systems',
          type: 'Extensions',
          discipline: 'Architecture',
          version: '2025',
          category: 'Architecture',
          icon: 'https://e7.pngegg.com/pngimages/169/472/png-clipart-microstation-autocad-computer-aided-design-computer-software-bentley-systems-bentley-miscellaneous-blue-thumbnail.png',
        },
        {
          id: 9,
          name: 'OpenBuildings',
          applications: 'OpenBuildings',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Bentley Systems',
          type: 'Macros',
          discipline: 'MEP',
          version: '2025',
          category: 'Macros',
          icon: 'https://www.bentley.com/wp-content/uploads/2022/04/openbuildings-software-logo-black-100X100.svg',
        },
        {
          id: 10,
          name: 'OpenRoads',
          applications: 'OpenRoads',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Bentley Systems',
          type: 'Macros',
          discipline: 'MEP',
          version: '2024',
          category: 'MEP',
          icon: 'https://yt3.googleusercontent.com/ytc/AIdro_mjLL8IVlBXb2pjpgc0kVHCVnjeHWK9x1yYmzfFbPTlFQ=s900-c-k-c0x00ffffff-no-rj',
        },
        {
          id: 11,
          name: 'ArcGIS',
          applications: 'ArcGIS',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'ESRI',
          type: 'Macros',
          discipline: 'Structure',
          version: '2025',
          category: 'Macros',
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/ArcGIS_logo.png/600px-ArcGIS_logo.png',
        },
        {
          id: 12,
          name: 'Rhino',
          applications: 'Rhino',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'McNeel & Associates',
          type: 'Dynamo',
          discipline: 'MEP',
          version: '2023',
          category: 'Dynamo',
          icon: 'https://img.icons8.com/?size=512&id=zbxme5NaU9Uj&format=png',
        },
        {
          id: 13,
          applications: 'Revit',
          name: 'Place Flex Pipe',
          description: 'PlaceFlexPipe is a Revit add-in that automates the creation of flexible pipes by allowing users to simply select existing model lines within the Revit model. This tool simplifies the process of placing flexible piping by interpreting model lines as routing paths and generating properly configured flex pipes along those paths.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'MEP',
          version: '2024',
          category: 'MEP',
        },
        {
          id: 14,
          applications: 'Revit',
          name: 'Conduit Pacement',
          description: 'addin to get  categorize real conduit fittings and fake ones and generating families with conduits and fake fittings to be placed in the model.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'MEP',
          version: '2024',
          category: 'MEP',
        },
        {
          id: 15,
          applications: 'Revit',
          name: 'Adjust Parameters',
          description: 'This Revit add-in automates the process of setting and managing parameters for assemblies within a Revit project.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2024',
          category: 'Structure',
        },
        {
          id: 16,
          applications: 'Revit',
          name: 'Numbering',
          description: 'The Dupod Structure Numbering Tool is a powerful Autodesk Revit add-in designed to streamline the process of assigning custom parameters and calculating material quantities, specifically for screws and glue in BIM- based modular construction.This latest enhancement expands its functionality, ensuring broader compatibility with structural framing elements and improving data accuracy for seamless integration with digital workflows.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2024',
          category: 'Structure',
        },
        {
          id: 17,
          applications: 'Revit',
          name: 'Family Paramerters',
          description: 'This Revit add-in automates the process of importing parameter values from Excel spreadsheets and populating them into both nested families and system families within a Revit project.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2024',
          category: 'Structure',
        },
        {
          id: 18,
          applications: 'Revit',
          name: 'Asset Manager',
          description: 'This feature allows users to automatically copy elements from linked Revit models into a federated model while maintaining their original locations and assigning them to the correct Worksets.This aims to streamline asset management and ensure each element is unique and properly categorized.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2024',
          category: 'Structure',
        },
        {
          id: 19,
          applications: 'Revit',
          name: 'Revit View Template',
          description: 'The "Customize Links Template" Revit Add-in empowers the MEP team to automate the application of custom link settings for internal links, such as Architectural and Structural links. These settings vary between shop drawings and production drawings but remain consistent across different pods. The add-in shall allow users to create, save, and manage presets, enabling the seamless application of predefined settings at the start of work on each pod, thereby enhancing efficiency and reducing manual errors.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'MEP',
          version: '2025',
          category: 'MEP',
        },
        {
          id: 20,
          applications: 'Revit',
          name: 'MEP Clash Solving Tool',
          description: 'The MEP Clash Solving Tool is a Revit add-in designed to automate clash detection and resolution for Mechanical (ME) and Electrical (EL) utilities that commonly run at the same level.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'MEP',
          version: '2025',
          category: 'MEP',
        },
      ]);
    }, 500)
  );
};
