import { AppModel } from '../types/App';

export const fetchApps = async (): Promise<AppModel[]> => {
  return new Promise((resolve) =>
    setTimeout(() => {
      resolve([        
        {
          id: 1,
          name: 'Revit',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://i0.wp.com/www.parallaxteam.com/wp-content/uploads/2022/04/2022-04-07_12-28-24-1.png?resize=209%2C218&ssl=1',
          type: 'Extensions',
          vendor: 'Autodesk',
          discipline: 'Architecture',
          version: '2024',
          category: 'Architecture',
        },
        {
          id: 2,
          name: 'AutoCAD',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://play-lh.googleusercontent.com/y92LD5c5rdlNfquCy-YPNIvdnS4ISEL05wickp28OLya8WlmWQwXfAP0Yys9iTssny3K',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Architecture',
          version: '2023',
          category: 'Architecture',
        },
        {
          id: 3,
          name: 'Inventor',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://www.imaginit.com/Portals/4/ImageCache/ProductDetails/1_autodesk-inventor-professional-product-icon-128@2x.png',
          type: 'Addins',
          vendor: 'Autodesk',
          discipline: 'Structure',
          version: '2023',
          category: 'Structure',
        },
        {
          id: 4,
          name: 'Navisworks',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          icon: 'https://damassets.autodesk.net/content/dam/autodesk/www/product-imagery/svg/product-icon/full/navisworks-manage-full-product-icon.svg',
          type: 'Dynamo',
          vendor: 'Autodesk',
          discipline: 'MEP',
          version: '2023',
          category: 'Dynamo',
        },
        {
          id: 5,
          name: 'Tekla Structures',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Trimble',
          type: 'Extensions',
          discipline: 'Structure',
          version: '2024',
          category: 'Creative',
          icon: 'https://cdn-icons-png.flaticon.com/512/1828/1828884.png',
        },
        {
          id: 6,
          name: 'Tekla Structures Designer',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Trimble',
          type: 'Extensions',
          discipline: 'Structure',
          version: '2024',
          category: 'Development',
          icon: 'https://cdn-icons-png.flaticon.com/512/2541/2541991.png',
        },
        {
          id: 7,
          name: 'SketchUp',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Trimble',
          type: 'Addins',
          discipline: 'Architecture',
          version: '2023',
          category: 'Tools',
          icon: 'https://cdn-icons-png.flaticon.com/512/3304/3304562.png',
        },
        {
          id: 8,
          name: 'BuildSim',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Bentley Systems',
          type: 'Simulation',
          discipline: 'Civil',
          version: '2.5',
          category: 'Simulation',
          icon: 'https://cdn-icons-png.flaticon.com/512/3132/3132693.png',
        },
        {
          id: 9,
          name: 'PlanIt',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Bentley Systems',
          type: 'Management',
          discipline: 'Project Management',
          version: '1.2',
          category: 'Productivity',
          icon: 'https://cdn-icons-png.flaticon.com/512/1828/1828843.png',
        },
        {
          id: 10,
          name: 'DrawLine',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'Bentley Systems',
          type: 'Design',
          discipline: 'Art',
          version: '4.0',
          category: 'Creative',
          icon: 'https://cdn-icons-png.flaticon.com/512/167/167707.png',
        },
        {
          id: 11,
          name: 'CodeAnalyzer',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'ESRI',
          type: 'Development',
          discipline: 'Software',
          version: '1.4',
          category: 'Development',
          icon: 'https://cdn-icons-png.flaticon.com/512/2421/2421114.png',
        },
        {
          id: 12,
          name: 'GeoMap Viewer',
          description: 'The goal of this feature is to enhance and upgrade an existing Revit add-in used by the structural team. The add-in should enable more efficient and flexible framing configurations, including improved management of common settings, wall framing, and profile configurations. The tool should be capable of saving, modifying, and sharing these configurations for use in various projects, with the flexibility to integrate with multiple versions of Revit (2024 and later). This will help streamline workflows, improve user productivity, and ensure the software is aligned with the structural teams specific needs.',
          vendor: 'McNeel & Associates',
          type: 'GIS',
          discipline: 'Geography',
          version: '3.0',
          category: 'Mapping',
          icon: 'https://cdn-icons-png.flaticon.com/512/684/684908.png',
        }
      ]);
    }, 500)
  );
};
