import { AppModel } from '../types/App';

export const fetchApps = async (): Promise<AppModel[]> => {
  return new Promise((resolve) =>
    setTimeout(() => {
      resolve([
        {
          id: 1,
          name: 'Visual Studio',
          description: 'IDE by Microsoft',
          icon: 'https://cdn-icons-png.flaticon.com/512/1828/1828884.png',
          type: 'Tool',
          vendor: 'Microsoft',
          discipline: 'Development',
          version: '2022',
          category: 'Development',
        },
        {
          id: 2,
          name: 'Photoshop',
          description: 'Photo editing',
          icon: 'https://cdn-icons-png.flaticon.com/512/3304/3304562.png',
          type: 'Utility',
          vendor: 'Adobe',
          discipline: 'Design',
          version: '2023',
          category: 'Design',
        },
        {
          id: 3,
          name: 'SQL Server',
          description: 'Database system',
          icon: 'https://cdn-icons-png.flaticon.com/512/1828/1828884.png',
          type: 'Tool',
          vendor: 'Microsoft',
          discipline: 'Database',
          version: '2019',
          category: 'Database',
        },
        {
          id: 4,
          name: 'Slack',
          description: 'Team communication',
          icon: 'https://cdn-icons-png.flaticon.com/512/3304/3304562.png',
          type: 'Communication',
          vendor: 'Slack',
          discipline: 'Collaboration',
          version: '2024',
          category: 'Productivity',
        },
        {
          id: 5,
          name: 'DesignTool Pro',
          description: 'Powerful tool for creative designs.',
          vendor: 'Adobe',
          type: 'Design',
          discipline: 'Architecture',
          version: '1.0',
          category: 'Creative',
          icon: 'https://cdn-icons-png.flaticon.com/512/1828/1828884.png',
        },
        {
          id: 6,
          name: 'CodeEditor Max',
          description: 'Lightweight and powerful code editor.',
          vendor: 'Microsoft',
          type: 'Development',
          discipline: 'Software',
          version: '2.0',
          category: 'Development',
          icon: 'https://cdn-icons-png.flaticon.com/512/2541/2541991.png',
        },
        {
          id: 7,
          name: 'CalcMaster',
          description: 'Advanced calculator for engineering tasks.',
          vendor: 'CalcSoft',
          type: 'Utility',
          discipline: 'Math',
          version: '3.1',
          category: 'Tools',
          icon: 'https://cdn-icons-png.flaticon.com/512/3304/3304562.png',
        },
        {
          id: 8,
          name: 'BuildSim',
          description: 'Simulation tool for construction.',
          vendor: 'SimCorp',
          type: 'Simulation',
          discipline: 'Civil',
          version: '2.5',
          category: 'Simulation',
          icon: 'https://cdn-icons-png.flaticon.com/512/3132/3132693.png',
        },
        {
          id: 9,
          name: 'PlanIt',
          description: 'Project planning and tracking software.',
          vendor: 'PM Tools',
          type: 'Management',
          discipline: 'Project Management',
          version: '1.2',
          category: 'Productivity',
          icon: 'https://cdn-icons-png.flaticon.com/512/1828/1828843.png',
        },
        {
          id: 10,
          name: 'DrawLine',
          description: 'Sketching and drawing tool for artists.',
          vendor: 'CreativeSoft',
          type: 'Design',
          discipline: 'Art',
          version: '4.0',
          category: 'Creative',
          icon: 'https://cdn-icons-png.flaticon.com/512/167/167707.png',
        },
        {
          id: 11,
          name: 'CodeAnalyzer',
          description: 'Static code analysis and review assistant.',
          vendor: 'LintTools',
          type: 'Development',
          discipline: 'Software',
          version: '1.4',
          category: 'Development',
          icon: 'https://cdn-icons-png.flaticon.com/512/2421/2421114.png',
        },
        {
          id: 12,
          name: 'GeoMap Viewer',
          description: 'Visualize and analyze geographical data.',
          vendor: 'GeoTech',
          type: 'GIS',
          discipline: 'Geography',
          version: '3.0',
          category: 'Mapping',
          icon: 'https://cdn-icons-png.flaticon.com/512/684/684908.png',
        },
        {
          id: 13,
          name: 'FinancePro',
          description: 'Manage financial transactions with ease.',
          vendor: 'FinCorp',
          type: 'Finance',
          discipline: 'Accounting',
          version: '5.0',
          category: 'Finance',
          icon: 'https://cdn-icons-png.flaticon.com/512/1792/1792532.png',
        },
        {
          id: 14,
          name: 'NoteBoard',
          description: 'Your sticky notes organizer.',
          vendor: 'QuickApps',
          type: 'Utility',
          discipline: 'Organization',
          version: '1.1',
          category: 'Productivity',
          icon: 'https://cdn-icons-png.flaticon.com/512/892/892634.png',
        }
      ]);
    }, 500)
  );
};
